### PR TITLE
fix resource method names

### PR DESCRIPTION
**Pull request by ricventu**
Hi
i made this PR to solve the issue #31

### CODE REVIEW

**Comment by ricventu** [comment]
This will creare routes names:
```
  GET|HEAD        users ............................................................. users › UsersController@index
  POST            users ....................................................... users.store › UsersController@store
  PUT|PATCH       users/{user} .............................................. users.update › UsersController@update
  DELETE          users/{user} ............................................ users.destroy › UsersController@destroy
```

**Comment by freekmurze** [comment]
Could you add a test to ensure that this works?

**Comment by ricventu** [comment]
I had previously updated the test `will register routes with the correct http verbs for resourceful methods` by adding the route name.
Now I've also added the test `will register routes with the correct names for resourceful methods without adding already existing name for uri` to verify that when a URI is specified with the same name, the name is not duplicated. This is because to address this issue, the URI could be specified through Route uri, which would also generate the name. In this case, the name was being duplicated, but with this modification, it is filtered if it's duplicate at the end of the name.

The errors reported by `phpstan` are not caused by these PR and are also present in the main branch.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
